org: rindert
app: tee-together-backend
service: TeeTogether-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  role: arn:aws:iam::050451366469:role/lambda-full-access-dynamodb

resources:
  Resources:
    GolfUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GolfUser
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: S
        KeySchema:
          - AttributeName: UserId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        SSESpecification:
          SSEEnabled: true

functions:
  registerUser:
    handler: src/functions/registerUser.handler
    events:
      - httpApi:
          path: /users/register
          method: post
  
  getAllUsers:
    handler: src/functions/getUser.handler
    events:
      - httpApi:
          path: /users
          method: get

  loginUser:
    handler: src/functions/loginUser.handler
    events:
      - httpApi:
          path: /login
          method: post   

  registerRound:
    handler: src/functions/registerRound.handler
    events:
      - httpApi:
          path: /registerRound
          method: post             
