org: rindert
app: tee-together-backend
service: TeeTogether-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment:
    JWT_SECRET: ${ssm:/tee-together/JWT_SECRET}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-north-1:*:*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

# Minskar storleken på deployment-paketet och optimerar byggprocessen
package:
  individually: true
  exclude:
    - node_modules/aws-sdk/**  # AWS SDK ingår redan i Lambda
    - node_modules/**
    - .git/**
    - .vscode/**
    - .serverless/**
    - tests/**
    - docs/**
    - README.md
    - package-lock.json
    - yarn.lock
    - .env

# Använd Serverless inbyggda ESBuild för TypeScript-optimering
custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    target: "node20"
    exclude: ["aws-sdk"]

resources:
  Resources:
    GolfUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: GolfUser
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: S
          - AttributeName: Username
            AttributeType: S
        KeySchema:
          - AttributeName: UserId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: Username-index
            KeySchema:
              - AttributeName: Username
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    FriendRequestsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FriendRequests
        AttributeDefinitions:
          - AttributeName: RequesterId
            AttributeType: S
          - AttributeName: FriendId
            AttributeType: S
        KeySchema:
          - AttributeName: RequesterId
            KeyType: HASH
          - AttributeName: FriendId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    UserFriendsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserFriends
        AttributeDefinitions:
          - AttributeName: UserId
            AttributeType: S
          - AttributeName: FriendId
            AttributeType: S
        KeySchema:
          - AttributeName: UserId
            KeyType: HASH
          - AttributeName: FriendId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

functions:
  registerUser:
    handler: src/functions/registerUser.handler
    events:
      - httpApi:
          path: /users/register
          method: post

  getAllUsers:
    handler: src/functions/getUser.handler
    events:
      - httpApi:
          path: /users
          method: get

  loginUser:
    handler: src/functions/loginUser.handler
    events:
      - httpApi:
          path: /login
          method: post

  registerRound:
    handler: src/functions/registerRound.handler
    events:
      - httpApi:
          path: /registerRound
          method: post

  sendFriendRequest:
    handler: src/functions/sendFriendRequest.handler
    events:
      - httpApi:
          path: /friends/request
          method: post

  acceptFriendRequest:
    handler: src/functions/acceptFriendRequest.handler
    events:
      - httpApi:
          path: /friends/accept
          method: post

  searchGolfFriends:
    handler: src/functions/searchGolfFriends.handler
    events:
      - httpApi:
          path: /friends/search
          method: get

  removeFriend:
    handler: src/functions/removeFriend.handler
    events:
      - httpApi:
          path: /friends/remove
          method: delete
